title: TIIME
email: office@identinetics.com
description: >
  Trust and Internet Identity Meeting Europe<br>
  5-6 Feb 2018: Workshops and Meetings<br>
  7-8 Feb 2018: Unconference
baseurl: "/TiimeworkshopEu" # the subpath of your site, e.g. /blog
url: "https://rhoerbe.github.io" # the base hostname & protocol for your site

# Footer Settings
credit: Theme by <a href="https://themehall.com/">ThemeHall</a>

exclude:
  - Gemfile
  - Gemfile.lock
  - internal
  - identityworkshop.eu

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      use_jumbotron: "yes"
      show_on_menu: "yes"
      show_title: "yes"
